language: java
jdk: oraclejdk8
services:
  - mongodb
  - rabbitmq
  - redis-server
env:
  - TERM=dumb SI_FATAL_WHEN_NO_BEANFACTORY=true GRADLE_OPTS='-XX:MaxPermSize=512M -Xmx1024M'
script: ./gradlew check --debug

